// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6lGGSIZ20zdpf9y6WKSFCwPtVi99Vxrg',
    appId: '1:375208817009:web:2042cec2d2c08ece9546d0',
    messagingSenderId: '375208817009',
    projectId: 'facereco-9738f',
    authDomain: 'facereco-9738f.firebaseapp.com',
    databaseURL: 'https://facereco-9738f-default-rtdb.firebaseio.com',
    storageBucket: 'facereco-9738f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtb_7iIgLvKaz7PmK209z6UEOopoWf_H8',
    appId: '1:375208817009:android:c1178e77083d9f589546d0',
    messagingSenderId: '375208817009',
    projectId: 'facereco-9738f',
    databaseURL: 'https://facereco-9738f-default-rtdb.firebaseio.com',
    storageBucket: 'facereco-9738f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv1xJnG-EApNxP0e6XCsg3MOS1mGdr3cI',
    appId: '1:375208817009:ios:1aee81019b906f069546d0',
    messagingSenderId: '375208817009',
    projectId: 'facereco-9738f',
    databaseURL: 'https://facereco-9738f-default-rtdb.firebaseio.com',
    storageBucket: 'facereco-9738f.appspot.com',
    iosBundleId: 'com.example.facelogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv1xJnG-EApNxP0e6XCsg3MOS1mGdr3cI',
    appId: '1:375208817009:ios:f36c34c6bbe4faa89546d0',
    messagingSenderId: '375208817009',
    projectId: 'facereco-9738f',
    databaseURL: 'https://facereco-9738f-default-rtdb.firebaseio.com',
    storageBucket: 'facereco-9738f.appspot.com',
    iosBundleId: 'com.example.facelogin.RunnerTests',
  );
}
